extends: ../.eslintrc.yml

env:
  node: true
  browser: false

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: off
  '@typescript-eslint/no-restricted-imports':
    - error
    - patterns:
        - group:
            - '@ideanick/backend/**'
            - '!@ideanick/backend/**/'
            - '!@ideanick/backend/**/input'
          allowTypeImports: true
          message: 'Only types and input schemas are allowed to be imported from backend workspace'
